### ISSUE TITLE
Comparison of this extension with Enhanced Tracking Protection (Firefox 67.0.1 and above)

### ISSUE THREAD

**Issue by zzTUZComXjLi** [mozfreddyb/webext-firstpartyisolation#19]
I heard cookies are sandboxed now by default, thats why I'm asking.

**Comment by mozfreddyb** [comment]
Yeah, for the normal user I'd recommend using the built-in blocker instead of this extension.
The implementation in Firefox [*Enhanced Tracking Protection*](https://support.mozilla.org/en-US/kb/content-blocking) is much smoother, as it has heuristics for re-allowing third-party cookies if you have visited the 3rd-party site before with user interaction (e.g., not just through a redirect).
This greatly reduces breakage and unintended blocking.


However, first party isolation as implemented in this extension is a ban-hammer style approach that isolates all things. I think this might remain useful for some, but likely not all users.

**Comment by zzTUZComXjLi** [comment]
Thank you for the clarification!
